### ISSUE TITLE
About the code for Image Synthesis From Point Clouds

### ISSUE THREAD

**Issue by cbyan1003** [OpenGVLab/PonderV2#17]
Hi, thanks for your great work. I am trying to use your work as a frozen rendering module,  but I haven't found the code about Image Synthesis From Point Clouds. Could you share some simple scripts or ideas about how we can achieve this? Thank you.

**Comment by HaoyiZhu** [comment]
Hi, you could refer to the [render function](https://github.com/OpenGVLab/PonderV2/blob/main/ponder/models/ponder/ponder_indoor_base.py#L642) and remember to modify the ray sampling part to get all pixels. For more details, you can refer to [SDFStudio](https://github.com/autonomousvision/sdfstudio) where we borrow the rendering codes.

However, note that PonderV2's zero-shot rendering ability is not very good, compared to those rendering-specific methods, because we observe that better rendering performance may lead to worse downstream performance.
